name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run:  |
           yarn 
           npm run docs:build
           cd docs/.vitepress/dist
           git init
           git config --local user.name "ci"
           git add -A
           git commit -m 'deploy'
           git remote add origin https://scuzzlebuzzle:${GH_TOKEN}git@github.com:breadfruit/blog.git
           git checkout -b gh-pages
           git push -f --set-upstream origin gh-pages
    

